services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - "./data/db:/data/db"

  # backend:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - '6001:6001'
  #   volumes:
  #     - ./uploads:/usr/src/app/uploads

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'app-redis:/data'

volumes:
  app-redis:
      driver: local